// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tokens.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAllForUser = `-- name: DeleteAllForUser :exec
DELETE FROM
    tokens
WHERE
    scope = $1
    AND user_id = $2
`

type DeleteAllForUserParams struct {
	Scope  string    `json:"scope"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAllForUser(ctx context.Context, arg DeleteAllForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAllForUser, arg.Scope, arg.UserID)
	return err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO
    tokens (hash, user_id, expiry, scope)
VALUES
    ($1, $2, $3, $4)
`

type InsertTokenParams struct {
	Hash   []byte    `json:"hash"`
	UserID uuid.UUID `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.Exec(ctx, insertToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}
