// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS (
    SELECT
        1
    FROM
        users
    WHERE
        username = $1
)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    created_at,
    name,
    email,
    password_hash,
    activated,
    version,
    username
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Version,
		&i.Username,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id,
    created_at,
    name,
    email,
    password_hash,
    activated,
    version,
    username
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Version,
		&i.Username,
	)
	return i, err
}

const getUserForRefreshToken = `-- name: GetUserForRefreshToken :one
SELECT
    id,
    created_at,
    name,
    email,
    password_hash,
    activated,
    version
FROM
    users
    INNER JOIN tokens ON users.id = tokens.user_id
WHERE
    tokens.refresh_token = $1
    AND tokens.scope = $2
    AND tokens.expiry > $3
`

type GetUserForRefreshTokenParams struct {
	RefreshToken []byte    `json:"refresh_token"`
	TokenScope   string    `json:"token_scope"`
	TokenExpiry  time.Time `json:"token_expiry"`
}

type GetUserForRefreshTokenRow struct {
	ID           uuid.UUID `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	Activated    bool      `json:"activated"`
	Version      int32     `json:"version"`
}

func (q *Queries) GetUserForRefreshToken(ctx context.Context, arg GetUserForRefreshTokenParams) (GetUserForRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserForRefreshToken, arg.RefreshToken, arg.TokenScope, arg.TokenExpiry)
	var i GetUserForRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const getUserForToken = `-- name: GetUserForToken :one
SELECT
    id,
    created_at,
    name,
    email,
    password_hash,
    activated,
    version,
    username
FROM
    users
    INNER JOIN tokens ON users.id = tokens.user_id
WHERE
    tokens.hash = $1
    AND tokens.scope = $2
    AND tokens.expiry > $3
`

type GetUserForTokenParams struct {
	TokenHash   []byte    `json:"token_hash"`
	TokenScope  string    `json:"token_scope"`
	TokenExpiry time.Time `json:"token_expiry"`
}

func (q *Queries) GetUserForToken(ctx context.Context, arg GetUserForTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserForToken, arg.TokenHash, arg.TokenScope, arg.TokenExpiry)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
		&i.Version,
		&i.Username,
	)
	return i, err
}

const getUsersWithoutUsername = `-- name: GetUsersWithoutUsername :many
SELECT
    id,
    email
FROM
    users
WHERE
    username = 'default_username'
`

type GetUsersWithoutUsernameRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) GetUsersWithoutUsername(ctx context.Context) ([]GetUsersWithoutUsernameRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithoutUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithoutUsernameRow
	for rows.Next() {
		var i GetUsersWithoutUsernameRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :one
INSERT INTO
    users (name, email, password_hash, activated)
VALUES
    ($1, $2, $3, $4) RETURNING id,
    created_at,
    version
`

type InsertUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
	Activated    bool   `json:"activated"`
}

type InsertUserRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Version   int32     `json:"version"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Activated,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Version)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE
    users
SET
    name = $1,
    email = $2,
    password_hash = $3,
    activated = $4,
    version = version + 1
WHERE
    id = $5
    AND version = $6 RETURNING version
`

type UpdateUserParams struct {
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	Activated    bool      `json:"activated"`
	ID           uuid.UUID `json:"id"`
	Version      int32     `json:"version"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Activated,
		arg.ID,
		arg.Version,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE
    users
SET
    username = $1
WHERE
    id = $2
`

type UpdateUsernameParams struct {
	Username string    `json:"username"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUsername, arg.Username, arg.ID)
	return err
}
